version: '2'
services:
  # consul:
  #   image: consul
  #   container_name: consul
  #   hostname: consul
  #   networks:
  #     - internal
  #   restart: always
  #   volumes:
  #     - consul:/consul/data
  #   ports:
  #     - 8500:8500
  #   environment:
  #     - CONSUL_CLIENT_INTERFACE=0.0.0.0
  #   command: "agent -server -bootstrap"

  consul:
    image: progrium/consul
    container_name: consul
    hostname: consul
    networks:
      - internal
    restart: always
    volumes:
      - consul:/data
    ports:
      - 8500:8500
    command: "-server -bootstrap"
    
volumes:
  consul:

networks:
  internal: