version: '2'
services:
  consul:
    image: progrium/consul
    container_name: consul
    hostname: consul
    networks:
      - internal
    restart: always
    volumes:
      - consul:/data
    ports:
      - 8500:8500
    command: "-server -bootstrap"
    
volumes:
  consul:

networks:
  internal: